Repository BC-MAY-21-RN/proyecto-final-pf-n21-t2, pull requests merged in 2022-02, with the labels that each got.

#28 MockUp-Dog-Walker-screen
  App.js
  package-lock.json
  src/components/GenericCard/index.js
  src/components/LoginForm/index.js
  src/screens/DrawerScreens/SettingsWalker.js
  src/screens/DrawerScreens/UserSettingsWalker.js
  src/screens/WalkerDetailsClient.js
Labels: ready to merge, wip

#50 Issue#37 upload images of pets to firebase
  package-lock.json
  package.json
  src/assets/controllers/FileUpload.js
  src/screens/AddPet.js
  src/screens/Navigation/NavigationInit/index.js
Labels: review required

#53 Issue#40 functionality in add pet
  package-lock.json
  src/assets/controllers/FileUpload.js
  src/assets/controllers/firebaseShortcuts.js
  src/components/CustomButton/index.js
  src/hooks/usePetSignUp.js
  src/screens/AddPet.js
  src/screens/Navigation/NavigationInit/index.js
  src/screens/SignWelcome.js
Labels: review required

#59 Issue#39 review screen
  src/components/CustomRatings/index.js
  src/components/EnfasisText/styles.js
  src/components/GenericFlatList/index.js
  src/components/ReviewCard/index.js
  src/components/RoundImage/index.js
  src/components/UserPresentation/index.js
  src/components/WalkerCard/index.js
  src/screens/ClientDogWalker.js
  src/screens/Navigation/NavigationInit/index.js
  src/screens/Pets.js
  src/screens/Reviews.js
  src/screens/ToHireWalkerSelection.js
Labels: wip

#70 Added eye icon to password input
  package-lock.json
  src/components/CustomInput/index.js
  src/components/GenericSign/index.js
Labels: review required

#74 Issue#45 walk form mock up and function
  package-lock.json
  package.json
  src/components/CustomButton/index.js
  src/components/CustomButton/styles.js
  src/components/CustomDatePicker/index.js
  src/screens/FormTravel.js
  src/screens/Navigation/NavigationInit/index.js
  src/screens/ToHireWalkerSelection.js
Labels: review required

#78 Fix eye icon in password
  src/components/CustomInput/index.js
  src/screens/Navigation/NavigationInit/index.js
Labels: review required

#79 Fixed errors in inputs
  src/components/CustomInput/index.js
Labels: review required

#82 Redesign of the Logo
  src/assets/images/logo.png
  src/components/ImageLogo/styles.js
Labels: review required
